//! Demo-only payload types shared across `examples/`.
//!
//! These live in the library (not in `examples/`) because each
//! example is its own crate. Keeping the shared video type here makes
//! both binaries use the same generated `VideoFrameHeader`, so local
//! SHM and remote routing agree on the wire shape.
//!
//! Putting the type here gives both binaries the same concrete
//! `quicbit::demo::VideoFrame` and its generated
//! `quicbit::demo::VideoFrameHeader`, so SHM routing works.

/// Demo video frame. RGBA-packed `u32` pixels in row-major order
/// (`0x00RRGGBB`). The header (width, height, frame_no, stamp_ns)
/// is auto-generated by the `#[datapod::datapod]` macro and rides
/// in the fixed local header; pixels ride in the variable-length
/// payload.
#[datapod::datapod]
pub struct VideoFrame {
    pub width: u32,
    pub height: u32,
    pub frame_no: u64,
    pub stamp_ns: u64,
    #[dp(bytes)]
    pub pixels: Vec<u32>,
}
