//! Demo-only payload types shared across `examples/`.
//!
//! These live in the library (not in `examples/`) because each
//! example is its own crate, and a type defined per-crate has a
//! per-crate `core::any::type_name`, which iceoryx2 uses to match
//! service compatibility. A publisher's `Frame` defined in
//! `examples/video_pub.rs` and a subscriber's `Frame` defined in
//! `examples/video_sub.rs` would *look* identical but have
//! different type names and fail to attach.
//!
//! Putting the type here gives both binaries the same concrete
//! `quicbit::demo::VideoFrame` and its generated
//! `quicbit::demo::VideoFrameHeader`, so SHM routing works.

/// Demo video frame. RGBA-packed `u32` pixels in row-major order
/// (`0x00RRGGBB`). The header (width, height, frame_no, stamp_ns)
/// is auto-generated by the `#[datapod::datapod]` macro and rides
/// in the iceoryx2 user-header slot; pixels ride in the variable-
/// length slice payload.
#[datapod::datapod]
pub struct VideoFrame {
    pub width: u32,
    pub height: u32,
    pub frame_no: u64,
    pub stamp_ns: u64,
    #[dp(bytes)]
    pub pixels: Vec<u32>,
}
